name: veevex_

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  google_sign_in: ^5.2.4
  geolocator: ^8.2.0
  http: ^1.3.0 
  flutter_map: ^6.0.0  
  latlong2: ^0.9.1 